### ISSUE TITLE
Error on db migrate: option values must be strings

### ISSUE THREAD

**Issue by EMChamp** [TwilioDevEd/browser-calls-flask#158]
Hi all, I am following the steps on the readme and on Step 6 I try to run `python manage.py db upgrade` and I receive the following error:

`Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    manager.run()
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/alembic/script/base.py", line 481, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "migrations/env.py", line 22, in <module>
    config.set_main_option(
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/alembic/config.py", line 231, in set_main_option
    self.set_section_option(self.config_ini_section, name, value)
  File "/Users/rsunga/PycharmProjects/browser-calls-flask/venv/lib/python3.8/site-packages/alembic/config.py", line 258, in set_section_option
    self.file_config.set(section, name, value)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/configparser.py", line 1200, in set
    self._validate_value_types(option=option, value=value)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/configparser.py", line 1185, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: <flask_script.commands.Command object at 0x107625640>: option values must be strings
`

I'm using Mac OS X with Python 3.8 installed.

**Comment by bld010** [comment]
Hi @EMChamp ... It looks like there was an environment variable missing: `DATABASE_URI`. 
I used Postgres with this, so I created a new database called `browser-calls-flask` and `postgresql:///browser-calls-flask` is an example value for `DATABASE_URI`.

I have an M1 Chip and ran into some issues with the psycopg2 dependency. If you run into this, as well, there are some possible solutions listed [here](https://github.com/psycopg/psycopg2/issues/1216). The specific solution that worked for me was [this one](https://github.com/psycopg/psycopg2/issues/1216#issuecomment-849321945). 

#168 should resolve this issue.
